# based on https://github.com/MobileDevOps/flutter-sdk-image/blob/master/Dockerfile
FROM --platform=linux/amd64 ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive
ENV LANG en_US.UTF-8

# Add base environment
RUN apt-get -qq update
#    && apt-get -qqy --no-install-recommends install \
#    apt-utils \
#    build-essential \
#    openjdk-22-jdk \
#    openjdk-22-jre-headless \
#    software-properties-common \
#    libssl-dev \
#    libffi-dev \
#    python3-dev \
#    cargo \
#    pkg-config\
#    libstdc++6 \
#    libpulse0 \
#    libglu1-mesa \
#    openssh-server \
#    zip \
#    unzip \
#    curl \
#    lldb \
#    git > /dev/null \
#    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*